
stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - params.yaml
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - prepare.test_size
      - prepare.random_state
      - prepare.stratify

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/processed/train.csv
      - params.yaml
    metrics:
      - models/metrics.json:
          cache: false
    outs:
      - models/model.pkl
    params:
      - train.test_size
      - train.random_state
      - train.alpha
